apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-webhook
  labels:
    app: alert-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-webhook
  template:
    metadata:
      labels:
        app: alert-webhook
    spec:
      containers:
        - name: alert-webhook
          image: ghcr.io/<YOUR_GITHUB_USER>/grafana-llm-webhook:latest
          ports:
            - containerPort: 8080
          env:
            - name: GRAFANA_URL
              value: "http://grafana:3000"
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alert-webhook-secrets
                  key: GRAFANA_API_KEY
            - name: TEAMS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: alert-webhook-secrets
                  key: TEAMS_WEBHOOK_URL
            - name: OLLAMA_URL
              value: "http://ollama:11434/api/generate"
---
apiVersion: v1
kind: Service
metadata:
  name: alert-webhook
spec:
  selector:
    app: alert-webhook
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
