apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-llm-webhook
  labels:
    app: grafana-llm-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-llm-webhook
  template:
    metadata:
      labels:
        app: grafana-llm-webhook
    spec:
      imagePullSecrets:
        - name: ghcr-secret   # Added for GHCR private image authentication
      containers:
        - name: webhook
          # This line will be automatically updated by GitHub Actions
          image: ghcr.io/eciiidevsecops/llm-webhook/grafana-llm-webhook:2a44ad3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: GRAFANA_URL
              value: "http://grafana.monitoring.svc.cluster.local:3000"
            - name: GRAFANA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: grafana-secrets
                  key: api-key
            - name: TEAMS_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: teams-secrets
                  key: webhook
            - name: OLLAMA_URL
              value: "http://ollama:11434"
            - name: OLLAMA_MODEL
              value: "gemma2"
